@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Dec 16 10:18:40 +0100 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_14 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L lmb_v10_v3_0_14 -L lmb_bram_if_cntlr_v4_0_25 -L blk_mem_gen_v8_4_9 -L iomodule_v3_1_11 -L fifo_generator_v13_2_11 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot TB_ftdi_synchronous_245_behav xil_defaultlib.TB_ftdi_synchronous_245 xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_14 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L lmb_v10_v3_0_14 -L lmb_bram_if_cntlr_v4_0_25 -L blk_mem_gen_v8_4_9 -L iomodule_v3_1_11 -L fifo_generator_v13_2_11 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot TB_ftdi_synchronous_245_behav xil_defaultlib.TB_ftdi_synchronous_245 xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
